// Code generated by mockery v2.33.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NonceManager is an autogenerated mock type for the NonceManager type
type NonceManager struct {
	mock.Mock
}

// CheckNonce provides a mock function with given fields: nonce
func (_m *NonceManager) CheckNonce(nonce []byte) error {
	ret := _m.Called(nonce)

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = rf(nonce)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetNonce provides a mock function with given fields:
func (_m *NonceManager) GetNonce() ([]byte, error) {
	ret := _m.Called()

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SweepExpiredNonces provides a mock function with given fields:
func (_m *NonceManager) SweepExpiredNonces() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewNonceManager creates a new instance of NonceManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNonceManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *NonceManager {
	mock := &NonceManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
