/*
Copyright IBM Corp. All Rights Reserved.

SPDX-License-Identifier: Apache-2.0
*/
// Code generated by mockery v1.0.0

package mocks

import api "github.com/hyperledger/fabric-ca/api"
import mock "github.com/stretchr/testify/mock"

// Identity is an autogenerated mock type for the Identity type
type Identity struct {
	mock.Mock
}

// Revoke provides a mock function with given fields: req
func (_m *Identity) Revoke(req *api.RevocationRequest) (*api.RevocationResponse, error) {
	ret := _m.Called(req)

	var r0 *api.RevocationResponse
	if rf, ok := ret.Get(0).(func(*api.RevocationRequest) *api.RevocationResponse); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.RevocationResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*api.RevocationRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
