#!/bin/bash
#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# shellcheck source=/dev/null
source "$(cd "$(dirname "$0")" && pwd)/functions.sh"

CHECK=$(git diff --name-only --diff-filter=ACMRTUXB HEAD)
CHECK="$(filterExcludedAndGeneratedFiles "$CHECK")"
if [[ -z "$CHECK" ]]; then
  CHECK=$(git diff-tree --no-commit-id --name-only --diff-filter=ACMRTUXB -r HEAD^..HEAD)
  CHECK="$(filterExcludedAndGeneratedFiles "$CHECK")"
fi

if [[ -z "$CHECK" ]]; then
   echo "All files are excluded from having license headers"
   exit 0
fi

echo "Checking Go files for license headers ..."
missing=$(echo "$CHECK" | xargs ls -d 2>/dev/null | xargs grep -L "SPDX-License-Identifier")
if [[ -z "$missing" ]]; then
   echo "All files have SPDX-License-Identifier headers"
   exit 0
fi
echo "The following files are missing SPDX-License-Identifier headers:"
echo "$missing"
echo
echo "Please replace the Apache license header comment text with:"
echo "SPDX-License-Identifier: Apache-2.0"

missing=$(echo "$missing" | xargs ls -d 2>/dev/null | xargs grep -L "Apache License")
if [ -z "$missing" ]; then
   echo "All remaining files have Apache 2.0 headers"
   exit 0
fi

echo "The following files are missing license headers:"
echo "$missing"
exit 1
