#!/bin/sh
#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
OLD=$GOPATH/src/github.com/hyperledger/fabric-cop
NEW=$GOPATH/src/github.com/hyperledger/fabric-ca
if [ -d "$NEW" ]; then
   echo "$NEW already exists"
elif [ -d "$OLD" ]; then
   echo "Renaming $OLD to $NEW"
   mv $OLD $NEW
else
   echo "Neither $OLD nor $NEW exists"
fi
