#!/bin/bash

echo "Running all tests ..."
{
export PATH=$PATH:$GOPATH/bin

go get github.com/axw/gocov/...
go get github.com/AlekSi/gocov-xml

PKGS=`go list github.com/hyperledger/fabric-cop/... | grep -v /vendor/`

gocov test $PKGS | gocov-xml > coverage.xml

} | tee /tmp/test.results
echo "Finished running all tests"
SC=0
FAILURES=`awk '$1 != "ok" && $1 != "?"' /tmp/test.results`
if [ "$FAILURES" != "" ]; then
   echo "*** BEGIN FAILURES ***"
   echo "$FAILURES"
   echo "*** END FAILURES ***"
   SC=1
fi
INSUFFICIENT_COVERAGE=`awk '$1 == "?" || ($1 == "ok" && $5 != "100.0%" && substr($5, 0, length($5)-1) < 75)' /tmp/test.results`
if [ "$INSUFFICIENT_COVERAGE" != "" ]; then
   echo "*** BEGIN INSUFFICIENT TEST COVERAGE (less than 75%) ***"
   echo "$INSUFFICIENT_COVERAGE"
   echo "*** END INSUFFICIENT TEST COVERAGE (less than 75%) ***"
   SC=1
fi
exit $SC
