#!/bin/bash
#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#


function killAndRemove() {
  if [[ "$(docker ps -a -q -f name="${1}")" ]]; then
    docker rm -f "${1}"
  fi
}

function cleanup() {
  printf "\nCleaning up FVT Docker artifacts...\n"
  killAndRemove mysql
  killAndRemove postgres
  killAndRemove fabric-fvt
  if [[ "$(docker network ls -q -f name=fvtnet)" ]]; then
    docker network rm fvtnet
  fi
}

cleanup
docker network create fvtnet
docker run --network fvtnet -d --name postgres -e POSTGRES_PASSWORD=postgres postgres:11
docker run --network fvtnet -d --name mysql -v $(pwd)/.mysql_data/mysql:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=mysql mysql:5.7 mysqld --sql-mode=STRICT_TRANS_TABLES
docker run --network fvtnet --name fabric-fvt -v $(pwd):/opt/gopath/src/github.com/hyperledger/fabric-ca hyperledger/fabric-ca-fvt

trap cleanup EXIT
