# Copyright the Hyperledger Fabric contributors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: $(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.rrr)
trigger:
- master
- release-2.*
- release-1.4
pr:
- master
- release-2.*
- release-1.4

variables:
  GOPATH: $(Agent.BuildDirectory)/go
  PATH: $(Agent.BuildDirectory)/go/bin:$(Agent.BuildDirectory)/go/src/github.com/hyperledger/fabric-ca/build/tools:/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin
  GOVER: 1.12.9

jobs:
- job: VerifyBuild
  pool:
    vmImage: ubuntu-16.04
  steps:
  - template: install_deps.yml
  - checkout: self
    path: 'go/src/github.com/hyperledger/fabric-ca'
    displayName: Checkout Fabric CA Code
  - script: make dist-all checks all-tests docs
    displayName: Run Unit and Integration Tests

- job: FVTTests
  pool:
    vmImage: ubuntu-16.04
  steps:
  - template: install_deps.yml
  - checkout: self
    path: 'go/src/github.com/hyperledger/fabric-ca'
    displayName: Checkout Fabric CA Code
  - script: make fvt-tests
    displayName: Run FVT Tests

- job: DocBuild
  pool:
    vmImage: ubuntu-16.04
  steps:
  - script: sudo apt-get clean && sudo apt-get update && sudo apt-get install -y python-minimal tox
    displayName: Install Tox
  - checkout: self
    path: 'go/src/github.com/hyperledger/fabric-ca'
    displayName: Checkout Fabric CA Code
  - script: tox -edocs
    displayName: Build Documentation
  - publish: 'docs/_build/html'
    displayName: Publish Documentation
