FROM hyperledger/fabric-baseimage:_BASE_TAG_

#Based this Dockerfile from https://github.com/osixia/docker-openldap/blob/stable/image/Dockerfile

ADD payload/openldap.tar /container
RUN /container/build.sh

RUN groupadd -r openldap && useradd -r -g openldap openldap

RUN apt-get -y update \
    && /container/tool/add-service-available :ssl-tools \
	  && LC_ALL=C DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes --no-install-recommends \
       ldap-utils \
       openssl \
       slapd \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN /container/tool/install-service

ENTRYPOINT ["/container/tool/run"]

EXPOSE 389 636
