FROM hyperledger/fabric-baseos:_BASE_TAG_
ENV FABRIC_CA_HOME /etc/hyperledger/fabric-ca-server
RUN mkdir -p $FABRIC_CA_HOME /var/hyperledger/fabric-ca-server
COPY payload/fabric-ca-client /usr/local/bin
RUN chmod +x /usr/local/bin/fabric-ca-client
COPY payload/fabric-ca-server /usr/local/bin
RUN chmod +x /usr/local/bin/fabric-ca-server

# Copy the same certificates that are currently hardcoded into the peers
ADD payload/fabric-ca.tar.bz2 $FABRIC_CA_HOME

EXPOSE 7054
CMD fabric-ca-server start -b admin:adminpw
