FROM hyperledger/fabric-baseos:_BASE_TAG_
ENV CA_CFG_PATH /etc/hyperledger/fabric-ca
ENV CERT_PATH /.fabric-ca
RUN mkdir -p $CA_CFG_PATH /var/hyperledger/fabric-ca
COPY payload/fabric-ca /usr/local/bin

# Copy the configuration files
ADD payload/sampleconfig.tar.bz2 $CA_CFG_PATH

# Copy the same certificates that are currently hardcoded into the peers
ADD payload/certfiles.tar.bz2 $CERT_PATH

EXPOSE 7054
CMD fabric-ca server start -address 0.0.0.0 -config $CA_CFG_PATH/server-config.json
